### ISSUE TITLE
Installation problems on M1 Mac

### ISSUE THREAD

**Issue by boltzmann-brain** [ruizhang1996/optimal-sparse-regression-tree-public#1]
I've been trying to install this library on an M1 Mac (MacOS 12.6.1) and encountered the following problems:

1. If I install Boost, GMP, and Intel TBB using Homebrew, I get errors saying these libraries can't be found, even if I specify their paths with the `-L` option in the makefile and  specify `BOOST_ROOT` in my `./configure` command. I managed to avoid these errors once I did the following: A) Download and build GMP and Intel TBB from source. B) Install Boost using Conda.
2. After my workarounds in step 1, I'm able to run `./autobuild --configure --enable-tests` without errors. However, if I try to run `./autobuild --install-python`, I encounter errors that I suspect has to do with the ARM architecture not being supported.

Error 1 comes up if I run `./autobuild --install-python`:

```
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
```

Error 2 comes up if I run `./autobuild --test`:

```
Undefined symbols for architecture arm64:

  "_main", referenced from:

     implicit entry/start for main executable


ld: symbol(s) not found for architecture arm64
```

**Comment by rayyy-zhang** [comment]
Hi we can only reproduce Error 2 on a M1-chip Mac. We'll update our build files, please stay tuned.

**Comment by rayyy-zhang** [comment]
Tested on M1-mac, it should be fixed right now.
