### ISSUE TITLE
failing to install with pip.

### ISSUE THREAD

**Issue by cdd33** [ruizhang1996/optimal-sparse-regression-tree-public#2]
I am trying to install the repo using a blank codespace and pip.

Here is what I tried:

1. pip3 install  scikit-learn
2. pip3 install attrs packaging editables pandas sortedcontainers gmpy2 matplotlib
3. pip3 install gosdt
4. pip install distro
5. pip install git+https://github.com/ruizhang1996/optimal-sparse-regression-tree-public

This gives the following error:
'...CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.......'
...note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for osrt
  Running setup.py clean for osrt
Failed to build osrt'

**Comment by rayyy-zhang** [comment]
Hi, which OS are you using? If you are using macos or linux, you should be able to direct install osrt by entering

pip install osrt

If you are using windows, please git clone the repo and follow the doc/build.md to install

**Comment by cdd33** [comment]
Hi,
Thanks. I will give it a try.
Matt Beswick.
