### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by longyuxi** [ruizhang1996/optimal-sparse-regression-tree-public#4]
Hi,

I have been trying to run the example `.py` code and it does not seem to work. I installed via `git clone https://github.com/ruizhang1996/optimal-sparse-regression-tree-public`.

Then I changed lines 6 and 7 of the example Python code from the Readme to the following

```
from osrt.model.threshold_guess import compute_thresholds
from osrt.model.osrt import OSRT
```

And now it is giving me the error

```
...
File /usr/project/dlab/Users/jaden/optimal-sparse-regression-tree-public/osrt/model/osrt.py:6
      3 import time
      4 from numpy import array
----> 6 import osrt.libosrt as osrt  # Import the GOSDT extension
      7 # from osrt.model.encoder import Encoder
      8 # from osrt.model.imbalance.osdt_imb_v9 import bbound, predict  # Import the special objective implementation
      9 from osrt.model.tree_regressor import TreeRegressor  # Import the tree classification model

ModuleNotFoundError: No module named 'osrt.libosrt'
```

And if I change `osrt.py:6` to `import osrt`, it gives me the error

```
File /usr/project/dlab/Users/jaden/optimal-sparse-regression-tree-public/osrt/model/osrt.py:110, in OSRT.fit(self, X, y)
     97 def fit(self, X, y):
     98     """
     99     Parameters
    100     ---
   (...)
    107     trains the model so that this model instance is ready for prediction
    108     """
--> 110     self.__train__(X, y)
    112     return self
...
---> 58 osrt.configure(json.dumps(self.configuration, separators=(',', ':')))
     59 result = osrt.fit(dataset.to_csv(index=False))  # Perform extension call to train the model
     61 self.time = osrt.time()  # Record the training time

AttributeError: module 'osrt' has no attribute 'configure
```

**Comment by rayyy-zhang** [comment]
Hi,

Did you follow the instruction to install both C++ and python module? It seems the python module is not installed in the python you used to run the example code.

**Comment by longyuxi** [comment]
@ruizhang1996 Hi Rui, I am trying to directly run code from source. I ran `git clone https://github.com/ruizhang1996/optimal-sparse-regression-tree-public` and then executed the code above in the cloned repository. Thank you.

**Comment by rayyy-zhang** [comment]
Hi yuxi,

This is a C++ library wrapped by python surface, you need to install it before using it. You need to install by `pip3 install attrs packaging editables pandas sklearn sortedcontainers gmpy2 matplotlib
pip3 install osrt`. If this doesn't work for you, please follow the instruction info in readme to install from source code.   Best.

**Comment by rayyy-zhang** [comment]
mark as solved
