### ISSUE TITLE
pip3 install issues related to deprecated sklearn package, use scikit-learn instead

### ISSUE THREAD

**Issue by fitzpat-t** [ruizhang1996/optimal-sparse-regression-tree-public#5]
Hi, could you try to please  update the requirement.txt and pyproject.toml ? 
The issue is outlined [here](https://pypi.org/project/sklearn/)

At 1 Dec 2023, apparently using sklearn in the install instructions raises an exception. This means OSRT cannot be installed.  I've raised an issue with [TreeFarms as well ](https://github.com/ubc-systopia/treeFarms/issues/4) as it seems to be an issue for a few of the really great interpretable ML models.

**Comment by rayyy-zhang** [comment]
Thank you for bring this up, we've fixed it.
